#!/bin/bash

psql -U postgres -ppostgres -d postgres -h 172.17.0.1 -p 5432 -c "create user $1 with password '$1';"
psql -U postgres -ppostgres -d postgres -h 172.17.0.1 -p 5432 -c "create database $1 owner $1;"

